repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
        args: ["dbt/bigquery_privacy_demo/.", "--dialect", "bigquery"]
      - id: sqlfluff-fix
        args: ["dbt/bigquery_privacy_demo/.", "--dialect", "bigquery"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [--strict, -c=dbt/bigquery_privacy_demo/.yamllint]
