name: 'bigquery_privacy_demo'
version: '1.0.0'
config-version: 2

profile: 'bigquery_privacy_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  max_rows: 50
  policy_tag_path: "projects/bigquery-privacy-demo/locations/europe-west2/taxonomies/5829721592837763935/policyTags/"  # yamllint disable-line rule:line-length
  bank_account_number_policy_tag: "934947096368237236"
  dob_policy_tag: "314388894887310280"
  email_policy_tag: "8962487434236224306"
  free_text_policy_tag: "3411543870059956464"
  name_policy_tag: "6561325237916044672"
  phone_number_policy_tag: "7345421922681850963"
  post_code_policy_tag: "1050714110010310190"
  salary_policy_tag: "6086625436365280309"

# on-run-start:
#   - "{{ create_udfs('data_warehouse') }}"
#   - "{{ generate_row_sequence('data_warehouse') }}"

models:
  bigquery_privacy_demo:
    data_warehouse:
      materialized: table
      +persist_docs:
        columns: true
        relation: true
