name: 'bigquery_privacy_demo'
version: '1.0.0'
config-version: 2

profile: 'bigquery_privacy_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  max_rows: 50
  policy_tag_path: "projects/bigquery-privacy-demo/locations/europe-west2/taxonomies/3051515431972821694/policyTags/"  # yamllint disable-line rule:line-length
  bank_account_number_policy_tag: "4203843241979409841"
  dob_policy_tag: "5855148680878219069"
  email_policy_tag: "734617328132131678"
  free_text_policy_tag: "9130431369601315567"
  name_policy_tag: "2645123393881147413"
  phone_number_policy_tag: "681836166790352694"
  post_code_policy_tag: "3548318927837217600"
  salary_policy_tag: "7205731708012414017"

on-run-start:
  - "{{ generate_row_sequence('data_warehouse') }}"

models:
  bigquery_privacy_demo:
    data_warehouse:
      materialized: table
      +persist_docs:
        columns: true
        relation: true
