bigquery_privacy_demo:
  outputs:
    dev:
      dataset: data_warehouse
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west2
      method: oauth
      priority: interactive
      project: bigquery-privacy-demo
      threads: 5
      type: bigquery
  target: dev
